package istu.bacs.sybon;

public enum SybonTestResultStatus {
    OK,
    WRONG_ANSWER,
    PRESENTATION_ERROR,
    QUERIES_LIMIT_EXCEEDED,
    INCORRECT_REQUEST,
    INSUFFICIENT_DATA,
    EXCESS_DATA,
    OUTPUT_LIMIT_EXCEEDED,
    TERMINATION_REAL_TIME_LIMIT_EXCEEDED,
    ABNORMAL_EXIT,
    MEMORY_LIMIT_EXCEEDED,
    TIME_LIMIT_EXCEEDED,
    REAL_TIME_LIMIT_EXCEEDED,
    TERMINATED_BY_SYSTEM,
    CUSTOM_FAILURE,
    FAIL_TEST,
    FAILED,
    SKIPPED
}